
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josem
 */
public class jfrmRepaso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmRepaso.class.getName());

    /**
     * Creates new form jfrmRepaso
     */
    public jfrmRepaso() {
        initComponents();
        this.setSize(600, 650);
        this.setLocationRelativeTo(null);
        this.setTitle("Repaso Imagenes y Colores Santiago Turcios IVD");
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelColor = new javax.swing.JPanel();
        jlblImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jltsColores = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelColor.setBackground(new java.awt.Color(255, 255, 255));
        JPanelColor.setForeground(new java.awt.Color(255, 102, 153));
        JPanelColor.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout JPanelColorLayout = new javax.swing.GroupLayout(JPanelColor);
        JPanelColor.setLayout(JPanelColorLayout);
        JPanelColorLayout.setHorizontalGroup(
            JPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        JPanelColorLayout.setVerticalGroup(
            JPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jButton1.setText("Aceptar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jltsColores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Negro", "Rojo", "Amarillo", "Verde", "Azul" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jltsColores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jlblImagen)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(JPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jlblImagen)
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mensaje;
    mensaje = "El color seleccionado es " + jltsColores.getSelectedValue();
    String color = jltsColores.getSelectedValue();

    JOptionPane.showMessageDialog(this, mensaje);

    switch(color) {
        case "Rojo" : {
            JPanelColor.setBackground(Color.red);
            jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mario.png")));
            break;
        }
        case "Azul" : {
            JPanelColor.setBackground(Color.BLUE);
            jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sonic.png")));
            break;
        }
        case "Amarillo" : {
            JPanelColor.setBackground(Color.yellow);
            jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pikachu.png")));
            break;
        }
        case "Verde" : {
            JPanelColor.setBackground(Color.GREEN);
            jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shrek.png")));
            break;
        }
        case "Negro" : {
            JPanelColor.setBackground(Color.black);
            jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/amongus.png")));
        }
        default : JOptionPane.showMessageDialog(this, "Seleccione un Color");  
        break;
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmRepaso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JList<String> jltsColores;
    // End of variables declaration//GEN-END:variables
}
